"""Helper launcher.

This repository includes a PsychoPy Builder file `draw_face_blocktower.psyexp`.
To run:
1) Open PsychoPy (2023.2+ recommended)
2) File → Open → `draw_face_blocktower.psyexp`
3) Click the green Run button in Builder.
4) (Optional) File → Export HTML (for Pavlovia) or Export Python to `code/` for CLI use.

If you export Python, you can then run something like:
    python code/draw_face_blocktower_lastrun.py

Note: The `_lastrun.py` file is generated by PsychoPy and should generally be excluded from version control.
"""

if __name__ == "__main__":
    print(__doc__)